bounswe/bounswe2024group12

- app/mobile/Playlog/components/commons/SmallRatings.js
- app/mobile/Playlog/components/main/MainPageBanner.js
- app/mobile/Playlog/components/main/MainPageReviewCard.js
- app/mobile/Playlog/components/main/MainScreenComponents.js
- app/mobile/Playlog/components/main/ReviewListCard.js
Related issues: #145, #146, #147, #149 
The following components are implemented in the following directories:
- components/commons/SmallRatings.js
- components/main/MainPageBanner.js
- components/main/MainPageReviewCard.js
- components/main/ReviewListCard.js
> Feature (Mobile): Add review card, review list card, main page banner, and small ratings

- docker-compose.yaml
- frontend/Dockerfile
I simplified the Dockerfile and created a docker-compose.yaml file and tested it, after the merge with backend, the docker-compose file needs to be merged to a one comprehensive file.
> updated dockerfile and added docker-compose.yaml fiile

- frontend/README.md
> Frontend dev

- frontend/src/components/gamepage/GamePageComponents.jsx
- frontend/src/components/gamepage/TabComponent.jsx
- frontend/src/components/gamepage/TabComponent.module.css
- frontend/src/components/mainpage/MainPageComponents.jsx
- frontend/src/components/mainpage/MainPageReviewBox.jsx
- frontend/src/components/mainpage/MainPageReviewBox.module.css
- frontend/src/components/mainpage/MainPageReviewList.jsx
- frontend/src/pages/GamePage.jsx
Front-end for reviews. Needs to be tested after Isil and Arda's endpoints are deployed
> Frontend review

- backend/game/apps.py
- backend/game/urls.py
- backend/game/views.py
- backend/main/views.py
I'm fixing a crucial bug about game DB.
> bugfix: db called before init fixed

- backend/game/urls.py
- backend/game/views.py
I finalized Game and Main Page features.
> Finalize Main and Game Page Features

- frontend/src/components/common/Card.module.css
- frontend/src/components/common/ComponentLoader/ComponentLoader.jsx
- frontend/src/components/common/ComponentLoader/ComponentLoader.module.css
- frontend/src/components/common/Menu.jsx
- frontend/src/components/common/Menu.module.css
- frontend/src/components/gamepage/GameInfo.jsx
- frontend/src/components/gamepage/GameInfo.module.css
- frontend/src/components/gamepage/TabComponent.jsx
- frontend/src/components/gamepage/TabComponent.module.css
- frontend/src/components/mainpage/GameOfTheDay.jsx
- frontend/src/components/mainpage/GameOfTheDay.module.css
- frontend/src/components/mainpage/MainPageGameLists.jsx
- frontend/src/components/mainpage/MainPageGameLists.module.css
- fixed buggy images
- fixed overflowed contents
- added scrollable gamelists
- edited tab component
- added animation loaders
- cursor hover pointer fixes
> UI Developments

- backend/game/tests/test_views.py
I added different scenario tests for Search-game-by. Due to this function is dynamically complex tests are beneficial to dont break the page.
> Unit Test for  Search-game-by

- frontend/.gitignore
- frontend/README.md
- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/public/robots.txt
- frontend/src/App.css
- frontend/src/App.js
- frontend/src/index.css
- frontend/src/index.js
- frontend/src/pages/HomePage.jsx
- frontend/src/pages/LoginPage.jsx
- frontend/src/pages/SignUpPage.jsx
Initialized react app, added mock login signup home page. #258
> init: login-signup-home page

- frontend/src/App.js
- frontend/src/components/Login.jsx
- frontend/src/components/commentpage/Comment.jsx
- frontend/src/components/commentpage/CommentCard.jsx
- frontend/src/components/commentpage/ShareComment.jsx
- frontend/src/components/homepage/Feed.jsx
- frontend/src/components/homepage/Post.jsx
- frontend/src/components/homepage/SharePost.jsx
- frontend/src/pages/CommentPage.jsx
Resolve #309, read relevant comments for more info
> 309 enhance post mechanism

- frontend/src/components/archivepage/ArchiveCard.jsx
- frontend/src/components/archivepage/GameScreen.jsx
- frontend/src/components/archivepage/ShareComment.jsx
- frontend/src/components/commentpage/CommentCard.jsx
- frontend/src/components/homepage/Feed.jsx
- frontend/src/components/homepage/Post.jsx
this pr includes:
-adding comments and displaying comments in each move, accordance with backend
-making advanced search on games, accordance with backend
-clicking games and examining them step by step, accordance with backend
-functionality of pgn to fen notation convertion
-like bug fix
resolves #328 resolves #327 resolves #326 resolves #325
> milestone 2 deliverables

- frontend/.babelrc
- frontend/__mocks__/chessboardjsx.js
- frontend/jest.config.js
- frontend/package-lock.json
- frontend/package.json
- frontend/setupTests.js
- frontend/src/components/__tests__/HomeCard.test.jsx
The test suite validates the following functionality:
- The HomeCard displays appropriate views based on user authentication status and performs necessary health checks for logged-in users.
- For Feed functionality, tests ensure posts render with their associated like counts and SharePost visibility adapts to user authentication state.
- Post component tests verify content rendering, user interactions like liking and deleting posts, and proper chess position display when FEN notation is present.
- SharePost validation covers form elements, submission handling, content type support including images and chess positions, and tag management. The tests also verify proper feedback through success messages and preview functionality.
Run the test suite with:
```npm test```
> unit test environment and tests for homepage

- app/backend/api_core/settings.py
- app/backend/v1/apps/puzzle/admin.py
- app/backend/v1/apps/puzzle/apps.py
- app/backend/v1/apps/puzzle/models.py
- app/backend/v1/apps/puzzle/tests.py
- app/backend/v1/apps/puzzle/urls.py
- app/backend/v1/apps/puzzle/views.py
- app/backend/v1/urls.py
In this PR, I have:
Created the following endpoints:
1.	GET /puzzle/daily
2.	GET /puzzle/random
3.	GET /puzzle/angles
4.	GET /puzzle/{id}
•	Added test cases for all endpoints.
•	Documented the endpoints using Swagger.
Detailed explanations also available under commits.
> Backend puzzles

- app/backend/v1/apps/accounts/tests.py
- app/backend/v1/apps/accounts/urls.py
- app/backend/v1/apps/accounts/views.py
- Added two endpoints : one returns current user's info including bookmarks, likes, followers, following, and posts; and the other one returns another user's info including likes, followers, following, and posts.
- Added unit tests for the functionalities of these endpoints.
- Updated Swagger documentation and URL paths accordingly.
(More details are in commit descriptions.)
> Backend user page endpoint

- project/Mobile/ProfileScreen.js
Profile screen is implemented for the mobile app.
> add: profile screen

- app/backend/v1/apps/games/views.py
Due to we will show the same screen at the client app, created endpoint to store game in our db and return our db result.
> Improve Master Games endpoint

- app/backend/v1/apps/accounts/tests.py
- app/backend/v1/apps/accounts/urls.py
- app/backend/v1/apps/accounts/views.py
- Parameter user_id:int is changed to username:string after the request from frontend team.
> fix parameter for get_other_user_page endpoint

- frontend/src/App.js
- frontend/src/components/commentpage/CommentCard.jsx
- frontend/src/components/common/Navbar.jsx
- frontend/src/components/homepage/Feed.jsx
- frontend/src/components/homepage/HomeCard.jsx
- frontend/src/components/homepage/Post.jsx
- frontend/src/components/homepage/SharePost.jsx
- frontend/src/components/profilepage/ProfileCard.jsx
- frontend/src/pages/ProfilePage.jsx
added features:
-filtering option in feed
-follower only function in feed
-bug fixes in feed
-tag selection in posts
-profile page of own
-my posts page in profile
> Isil m3/frontend

- frontend/src/components/homepage/Post.jsx
- frontend/src/components/profilepage/ProfileCard.jsx
> feat:added bookmarked posts

- frontend/src/components/homepage/Feed.jsx
> feat:handle followed only posts
